### ISSUE TITLE
Update project to use the `vonage` gem

### ISSUE THREAD

**Issue by bencgreenberg** [nexmo-community/nexmo-rails-telephone-game-vapi#9]
This project uses the `nexmo` gem, but it should be updated to use the new `vonage` Ruby SDK gem: https://github.com/vonage/vonage-ruby-sdk. 

The `Gemfile` and code will need to be updated accordingly.

Bonus: Add tests to validate the success of the refactor! 🌟

**Comment by rafaeelaudibert** [comment]
This looks something that I can do! Will give it a go (if you could assign it to me, i'd be glad).

**Comment by bencgreenberg** [comment]
Hey @rafaeelaudibert, I see my friend @martyndavies has assigned himself to review your PR, but I just want to say how much we appreciate the effort you put into it! Happy Hacktoberfest! 🙌

**Comment by lornajane** [comment]
We loved it so much that we included it our hacktoberfest stream yesterday! https://www.twitch.tv/videos/757575176
